CREATE TABLE PLATEAU
(
	ID_PLATEAU BIGINT NOT NULL PRIMARY KEY,
	DIRECTION VARCHAR(10) NOT NULL,
	LATITUDE  DOUBLE NOT NULL,  
	LONGITUDE DOUBLE NOT NULL
	);

CREATE TABLE PROBE
(
	ID_PROBE BIGINT NOT NULL PRIMARY KEY,
	ID_PLATEAU BIGINT NOT NULL,
	DIRECTION VARCHAR(10),
	LATITUDE DOUBLE NOT NULL,  
	LONGITUDE DOUBLE NOT NULL
);

ALTER TABLE PROBE
	ADD CONSTRAINT FK_PLATEAU FOREIGN KEY(ID_PLATEAU) REFERENCES PLATEAU(ID_PLATEAU);